# Site settings
title:       Wei
email:       weishigoname@hotmail.com
author:      Wei
description: "Welcome to Wei's blog."
baseurl:     ""
url:         "http://helloweishi.github.io/"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: weishigoname

# Social icons
show_social_icons: true
github_username: helloweishi
stackoverflow_id:
twitter_username: weishigoname
google_plus_id: weishigogo
linkedin_username: weishigoname
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
